package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dispositivo generated by hbm2java
 */
public class Dispositivo implements java.io.Serializable {

	private Integer iddispositivo;
	private Modelo modelo;
	private Tipodispositivo tipodispositivo;
	private Usuario usuario;
	private String nombre;
	private String descripcion;
	private Set sensoreses = new HashSet(0);

	public Dispositivo() {
	}

	public Dispositivo(Modelo modelo, Tipodispositivo tipodispositivo, Usuario usuario) {
		this.modelo = modelo;
		this.tipodispositivo = tipodispositivo;
		this.usuario = usuario;
	}

	public Dispositivo(Modelo modelo, Tipodispositivo tipodispositivo, Usuario usuario, String nombre,
			String descripcion, Set sensoreses) {
		this.modelo = modelo;
		this.tipodispositivo = tipodispositivo;
		this.usuario = usuario;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.sensoreses = sensoreses;
	}

	public Integer getIddispositivo() {
		return this.iddispositivo;
	}

	public void setIddispositivo(Integer iddispositivo) {
		this.iddispositivo = iddispositivo;
	}

	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	public Tipodispositivo getTipodispositivo() {
		return this.tipodispositivo;
	}

	public void setTipodispositivo(Tipodispositivo tipodispositivo) {
		this.tipodispositivo = tipodispositivo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getSensoreses() {
		return this.sensoreses;
	}

	public void setSensoreses(Set sensoreses) {
		this.sensoreses = sensoreses;
	}

}
