package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Operacion generated by hbm2java
 */
public class Operacion implements java.io.Serializable {

	private Integer idoperacion;
	private String descripcion;
	private Date fechaOperacion;
	private Set usuarios = new HashSet(0);

	public Operacion() {
	}

	public Operacion(String descripcion, Date fechaOperacion, Set usuarios) {
		this.descripcion = descripcion;
		this.fechaOperacion = fechaOperacion;
		this.usuarios = usuarios;
	}

	public Integer getIdoperacion() {
		return this.idoperacion;
	}

	public void setIdoperacion(Integer idoperacion) {
		this.idoperacion = idoperacion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaOperacion() {
		return this.fechaOperacion;
	}

	public void setFechaOperacion(Date fechaOperacion) {
		this.fechaOperacion = fechaOperacion;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
