package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private Integer idpersona;
	private Tipopersona tipopersona;
	private String cedula;
	private String nombre;
	private String apellido;
	private Date fechanacimiento;
	private String ciudad;
	private String parroquia;
	private String canton;
	private String tiposangre;
	private Set usuarios = new HashSet(0);

	public Persona() {
	}

	public Persona(Tipopersona tipopersona) {
		this.tipopersona = tipopersona;
	}

	public Persona(Tipopersona tipopersona, String cedula, String nombre, String apellido, Date fechanacimiento,
			String ciudad, String parroquia, String canton, String tiposangre, Set usuarios) {
		this.tipopersona = tipopersona;
		this.cedula = cedula;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechanacimiento = fechanacimiento;
		this.ciudad = ciudad;
		this.parroquia = parroquia;
		this.canton = canton;
		this.tiposangre = tiposangre;
		this.usuarios = usuarios;
	}

	public Integer getIdpersona() {
		return this.idpersona;
	}

	public void setIdpersona(Integer idpersona) {
		this.idpersona = idpersona;
	}

	public Tipopersona getTipopersona() {
		return this.tipopersona;
	}

	public void setTipopersona(Tipopersona tipopersona) {
		this.tipopersona = tipopersona;
	}

	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getParroquia() {
		return this.parroquia;
	}

	public void setParroquia(String parroquia) {
		this.parroquia = parroquia;
	}

	public String getCanton() {
		return this.canton;
	}

	public void setCanton(String canton) {
		this.canton = canton;
	}

	public String getTiposangre() {
		return this.tiposangre;
	}

	public void setTiposangre(String tiposangre) {
		this.tiposangre = tiposangre;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
