package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import dao.DatabaseOperations;
import dao.DatabaseOperationsSensores;



/**
 * Sensores generated by hbm2java
 */

@ManagedBean 
@SessionScoped
public class Sensores implements java.io.Serializable {

	private Integer idSensores;
	private Dispositivo dispositivo;
	private String siglas;
	private String unidad;
	private String tamano;
	private Set datoses = new HashSet(0);
	public static DatabaseOperationsSensores dbObj;
	private static final long serialVersionUID = 1L;
	private List<Sensores> listaSensores;
	public Sensores() {
	}

	public Sensores(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	public Sensores(Dispositivo dispositivo, String siglas, String unidad, String tamano, Set datoses) {
		this.dispositivo = dispositivo;
		this.siglas = siglas;
		this.unidad = unidad;
		this.tamano = tamano;
		this.datoses = datoses;
	}

	public Integer getIdSensores() {
		return this.idSensores;
	}

	public void setIdSensores(Integer idSensores) {
		this.idSensores = idSensores;
	}

	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public String getUnidad() {
		return this.unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	public String getTamano() {
		return this.tamano;
	}

	public void setTamano(String tamano) {
		this.tamano = tamano;
	}

	public Set getDatoses() {
		return this.datoses;
	}

	public void setDatoses(Set datoses) {
		this.datoses = datoses;
	}

	public void listaSensores() {

		dbObj = new DatabaseOperationsSensores();
		dbObj.listaSensores();

	}
	public List<Sensores> findAll(){
		dbObj = new DatabaseOperationsSensores();
		listaSensores= dbObj.listaSensores();
       return listaSensores;
   }
	
}
