package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipodispositivo generated by hbm2java
 */
public class Tipodispositivo implements java.io.Serializable {

	private Integer idtipodispositivo;
	private String descripcion;
	private Set dispositivos = new HashSet(0);

	public Tipodispositivo() {
	}

	public Tipodispositivo(String descripcion, Set dispositivos) {
		this.descripcion = descripcion;
		this.dispositivos = dispositivos;
	}

	public Integer getIdtipodispositivo() {
		return this.idtipodispositivo;
	}

	public void setIdtipodispositivo(Integer idtipodispositivo) {
		this.idtipodispositivo = idtipodispositivo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(Set dispositivos) {
		this.dispositivos = dispositivos;
	}

}
