package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tipopersona generated by hbm2java
 */
public class Tipopersona implements java.io.Serializable {

	private Integer idtipopersona;
	private String descripcion;
	private String observacion;
	private Set personas = new HashSet(0);

	public Tipopersona() {
	}

	public Tipopersona(String descripcion, String observacion, Set personas) {
		this.descripcion = descripcion;
		this.observacion = observacion;
		this.personas = personas;
	}

	public Integer getIdtipopersona() {
		return this.idtipopersona;
	}

	public void setIdtipopersona(Integer idtipopersona) {
		this.idtipopersona = idtipopersona;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Set getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set personas) {
		this.personas = personas;
	}

}
