package pojo;
// Generated 09/04/2019 19:54:04 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private Operacion operacion;
	private Persona persona;
	private Rol rol;
	private String nombre;
	private String username;
	private String password;
	private Integer nivel;
	private Set dispositivos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(Operacion operacion, Persona persona, Rol rol) {
		this.operacion = operacion;
		this.persona = persona;
		this.rol = rol;
	}

	public Usuario(Operacion operacion, Persona persona, Rol rol, String nombre, String username, String password,
			Integer nivel, Set dispositivos) {
		this.operacion = operacion;
		this.persona = persona;
		this.rol = rol;
		this.nombre = nombre;
		this.username = username;
		this.password = password;
		this.nivel = nivel;
		this.dispositivos = dispositivos;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public Operacion getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Operacion operacion) {
		this.operacion = operacion;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public Set getDispositivos() {
		return this.dispositivos;
	}

	public void setDispositivos(Set dispositivos) {
		this.dispositivos = dispositivos;
	}

}
